# Generated by Django 3.0.6 on 2020-07-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250, verbose_name='course')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=250, verbose_name='field name')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=250, verbose_name='exam name')),
                ('exam_date', models.DateField(verbose_name='exam date')),
                ('exam_period', models.IntegerField(verbose_name='exam period')),
                ('exam_note', models.TextField(blank=True, max_length=300, verbose_name='exam notes')),
                ('exam_secret_key', models.CharField(max_length=10, verbose_name='exam secret key')),
                ('exam_full_mark', models.IntegerField(max_length=10, verbose_name='exam full mark')),
                ('exam_pass_mark', models.IntegerField(max_length=10, verbose_name='exam pass mark')),
                ('exam_status', models.CharField(max_length=30, verbose_name='exam status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teacher.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teacher.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teacher.Field'),
        ),
    ]
