# Generated by Django 3.0.6 on 2020-07-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200713_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_unique_identifier',
            field=models.CharField(blank=True, max_length=120, verbose_name='exam unique identifier'),
        ),
    ]
