# Generated by Django 3.0.8 on 2020-08-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20200807_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='exam status'),
        ),
    ]
