# Generated by Django 3.0.8 on 2020-08-13 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20200812_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
