# Generated by Django 3.1 on 2020-10-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_auto_20201017_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_secret_key',
        ),
    ]
