# Generated by Django 3.1 on 2020-10-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_remove_exam_exam_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='encrypted_id',
            field=models.CharField(blank=True, max_length=400, verbose_name='encrypted id'),
        ),
    ]
