# Generated by Django 3.1 on 2020-10-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_exam_encrypted_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='encrypted_id',
        ),
    ]
