# Generated by Django 3.1 on 2020-10-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_exam_encrypted_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
