# Generated by Django 3.1 on 2020-10-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_loggedinuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
