# Generated by Django 3.1 on 2020-10-12 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0010_auto_20200815_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_grade_name', models.CharField(max_length=120, verbose_name='grade name')),
                ('student_grade_rate', models.FloatField(verbose_name='grade rate')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_response_text', models.TextField(verbose_name='answer here')),
                ('student_response_degree', models.FloatField(verbose_name='student degree')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_status', models.CharField(blank=True, max_length=30, verbose_name='exam status')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamDegrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_total_score', models.FloatField(verbose_name='student total degree')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentgrade')),
            ],
        ),
    ]
